title: qbix
theme: minima

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

header_pages:
  - docs/qbi-format.md

defaults:
  - scope:
      path: README.md
    values:
      layout: page
      permalink: /

exclude:
  - Cargo.*
  - LICENSE
  - build.rs
  - include/
  - paper/data/
  - paper/figures/
  - paper/scripts/
  - paper/work/
  - paper/paper.bib
  - paper/paper.md
  - paper/README.md
  - renovate.json
  - src/
  - target/
  - tests/
  - ".*"
