title: qbix
theme: minima

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

header_pages:
  - docs/qbi-format.md

defaults:
  - scope:
      path: README.md
    values:
      layout: page
      permalink: /

exclude:
  - Cargo.*
  - LICENSE
  - build.rs
  - include/
  - renovate.json
  - src/
  - target/
  - tests/
  - ".*"
